sudo: true

language: php

env:
  global:
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle/jre"
    - ES_VERSION="5.4.0"
    - ES_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.zip"

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  include:
    - php: 5.6
    - php: 7.0

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - sudo apt-get install -y oracle-java8-set-default
  - |
    if [[ $SYMFONY__PHPCR__TRANSPORT = jackrabbit ]]; then
        if [ ! -f downloads/jackrabbit-standalone-$JACKRABBIT_VERSION.jar ]; then
            cd downloads
            wget http://archive.apache.org/dist/jackrabbit/$JACKRABBIT_VERSION/jackrabbit-standalone-$JACKRABBIT_VERSION.jar
            cd -
        fi
        java -jar downloads/jackrabbit-standalone-$JACKRABBIT_VERSION.jar > /dev/null &
    fi
  - composer self-update
  - curl -L -o elasticsearch.zip ${ES_DOWNLOAD_URL}
  - unzip elasticsearch.zip
  - ./elasticsearch-*/bin/elasticsearch -d

install:
  - travis_retry composer install --no-interaction
  - composer info -i
  - ./tests/app/console ongr:es:index:create -m default
  - ./tests/app/console ongr:es:index:create -m live

script:
  - ./vendor/bin/phpunit

